### ISSUE TITLE
Allow the user to join a session

### ISSUE THREAD

**Issue by Zalerys** [arthur-fontaine/yvees#15]
**Tasks**

- [ ] Create a home page
- [x] Create the card component
- [x] Create the button component
- [x] Open the camera when we click on the scan button
- [x] When a QR Code is detected, pass the content found on the QR Code to the `joinSession` function (see #25)

**Screenshot**

![Image](https://github.com/arthur-fontaine/yvees/assets/57626613/21f47d40-4690-4304-9384-4c7e3cfeb0b1)

![Image](https://github.com/arthur-fontaine/yvees/assets/57626613/1d172e57-8886-48fc-bcf0-f3017d1fbdea)
