### ISSUE TITLE
Create the authentication screen on the mobile app

### ISSUE THREAD

**Issue by Zalerys** [arthur-fontaine/yvees#3]
**Tasks**

- [ ] Create the authentication screen
- [ ] Create the button component (with "primary" and "secondary" variants)
- [ ] Create the input component
- [ ] Create the custom flow using Clerk

**Resources**

[Documentation to use Clerk with Expo]( https://clerk.com/docs/quickstarts/expo)

**Screenshots**

![Image](https://github.com/arthur-fontaine/yvees/assets/57626613/50b31a7a-8ba3-4c5d-9bab-93f5d5d77540)
